// Writes the legal-page drafts Joseph approves, generated from the same content
// modules the pages render, so the two cannot drift apart.
// Run: node scripts/legal-drafts.mjs
import fs from 'node:fs';
import path from 'node:path';
import * as privacy from '../src/content/privacyPolicy.js';
import * as cookie from '../src/content/cookiePolicy.js';

const DIR = path.resolve('docs/drafts/t4');
fs.mkdirSync(DIR, { recursive: true });

function banner(title, module, wo, route) {
  return [
    `# ${title} — draft for approval`,
    '',
    `> Generated from \`src/content/${module}\` by \`scripts/legal-drafts.mjs\`.`,
    '> Do not edit this file by hand: edit the content module and regenerate,',
    '> otherwise the page and this draft stop matching.',
    '>',
    `> This is the wording of \`${route}\`, for ${wo}. Joseph approves it.`,
    '',
    '---',
    '',
  ];
}

function table(head, rows) {
  return [
    `| ${head.join(' | ')} |`,
    `|${head.map(() => '---').join('|')}|`,
    ...rows.map((r) => `| ${r.join(' | ')} |`),
  ];
}

// ---- privacy policy -------------------------------------------------------
{
  const out = banner('Privacy Policy', 'privacyPolicy.js', 'WO-4.10', '/privacy-policy');
  out.push('> Decisions still outstanding are in `for-joseph-WO-4.10.md` beside this file.');
  out.push('');
  out.push(`**Penn Jets LLC. Last updated ${privacy.LAST_UPDATED}.**`);
  out.push('');
  out.push(privacy.INTRO);
  out.push('');
  out.push('## The short version');
  out.push('');
  for (const line of privacy.SHORT_VERSION) out.push(`- ${line}`);

  for (const s of privacy.SECTIONS) {
    out.push('');
    out.push(`## ${s.title}`);
    for (const p of s.body || []) { out.push(''); out.push(p); }
    if (s.table) { out.push(''); out.push(...table(s.table.head, s.table.rows)); }
    if (s.list) { out.push(''); for (const item of s.list) out.push(`- ${item}`); }
    for (const p of s.after || []) { out.push(''); out.push(p); }
  }

  out.push('');
  out.push('## Contact');
  out.push('');
  out.push(`${privacy.CONTACT.name}  `);
  out.push(`${privacy.CONTACT.address}  `);
  out.push(`${privacy.CONTACT.email}  `);
  out.push(`${privacy.CONTACT.phone}`);
  out.push('');

  const file = path.join(DIR, 'privacy-policy.md');
  fs.writeFileSync(file, out.join('\n'));
  console.log(`wrote ${file} (${out.length} lines, ${privacy.SECTIONS.length} sections)`);
}

// ---- cookie policy --------------------------------------------------------
{
  const out = banner('Cookie Policy', 'cookiePolicy.js', 'WO-4.12', '/cookie-policy');
  out.push(`**Penn Jets LLC. Last updated ${cookie.LAST_UPDATED}.**`);
  out.push('');
  out.push(cookie.INTRO);
  out.push('');
  out.push(`## ${cookie.HEADLINE}`);
  for (const p of cookie.HEADLINE_BODY) { out.push(''); out.push(p); }
  out.push('');
  out.push('## What is actually stored');
  out.push('');
  out.push(`Measured on ${cookie.LAST_UPDATED} in a browser profile with nothing in it.`);
  out.push('');
  out.push(...table(cookie.INVENTORY.head, cookie.INVENTORY.rows));

  for (const s of cookie.SECTIONS) {
    out.push('');
    out.push(`## ${s.title}`);
    for (const p of s.body) { out.push(''); out.push(p); }
  }

  out.push('');
  out.push(cookie.RELATED);
  out.push('');

  const file = path.join(DIR, 'cookie-policy.md');
  fs.writeFileSync(file, out.join('\n'));
  console.log(`wrote ${file} (${out.length} lines, ${cookie.SECTIONS.length + 2} sections)`);
}
