// Writes docs/drafts/t4/privacy-policy.md from src/content/privacyPolicy.js,
// so the draft Joseph approves is generated from the same source the page
// renders and the two cannot drift apart. Run: node scripts/privacy-draft.mjs
import fs from 'node:fs';
import path from 'node:path';
import { LAST_UPDATED, INTRO, SHORT_VERSION, SECTIONS, CONTACT } from '../src/content/privacyPolicy.js';

const out = [];
out.push('# Privacy Policy — draft for approval');
out.push('');
out.push('> Generated from `src/content/privacyPolicy.js` by `scripts/privacy-draft.mjs`.');
out.push('> Do not edit this file by hand: edit the content module and regenerate,');
out.push('> otherwise the page and this draft stop matching.');
out.push('>');
out.push('> This is the wording of `/privacy-policy`, for WO-4.10. Joseph approves it.');
out.push('> Decisions still outstanding are in `for-joseph-WO-4.10.md` beside this file.');
out.push('');
out.push('---');
out.push('');
out.push(`**Penn Jets LLC. Last updated ${LAST_UPDATED}.**`);
out.push('');
out.push(INTRO);
out.push('');
out.push('## The short version');
out.push('');
for (const line of SHORT_VERSION) out.push(`- ${line}`);

for (const s of SECTIONS) {
  out.push('');
  out.push(`## ${s.title}`);
  for (const p of s.body || []) { out.push(''); out.push(p); }
  if (s.table) {
    out.push('');
    out.push(`| ${s.table.head.join(' | ')} |`);
    out.push(`|${s.table.head.map(() => '---').join('|')}|`);
    for (const r of s.table.rows) out.push(`| ${r.join(' | ')} |`);
  }
  if (s.list) { out.push(''); for (const item of s.list) out.push(`- ${item}`); }
  for (const p of s.after || []) { out.push(''); out.push(p); }
}

out.push('');
out.push('## Contact');
out.push('');
out.push(`${CONTACT.name}  `);
out.push(`${CONTACT.address}  `);
out.push(`${CONTACT.email}  `);
out.push(`${CONTACT.phone}`);
out.push('');

const file = path.resolve('docs/drafts/t4/privacy-policy.md');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, out.join('\n'));
const words = out.join(' ').replace(/[#|>*-]/g, ' ').split(/\s+/).filter(Boolean).length;
console.log(`wrote ${file} (${out.length} lines, ~${words} words, ${SECTIONS.length} sections)`);
